[2021-06-13 11:08:05,135::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID2210639:MainProcess): DNS Resolver Nameservers: ['1.1.1.1', '1.0.0.1', 'fd00::cece:1eff:fef3:5c2e', '2606:4700:4700::1111', '2606:4700:4700::1001']
[2021-06-13 11:08:05,135::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID2210639:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-06-13 11:08:05,136::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID2210639:MainProcess): DNS Resolver Port: 53
[2021-06-13 11:08:05,136::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID2210639:MainProcess): DNS Resolver timeout: 2.0
[2021-06-13 11:08:05,136::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID2210639:MainProcess): DNS Resolver lifetime: 5.0
[2021-06-13 11:08:05,136::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID2210639:MainProcess): DNS Resolver over TCP: False
[2021-06-13 11:08:05,139::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/config/preset.py:418@timeout](PID2210639:MainProcess): CONFIGURATION.timeout switched to 3.0
[2021-06-13 11:08:05,452::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/cli/dispatcher.py:118@__init__](PID2210639:MainProcess): CONFIGURATION:
{'adblock': False, 'aggressive': False, 'auto_continue': True, 'ci': False, 'ci_autosave_commit': 'PyFunceble - AutoSave', 'ci_autosave_final_commit': 'PyFunceble - Results', 'ci_autosave_minutes': 15, 'ci_branch': 'master', 'ci_distribution_branch': 'master', 'cli_decoding': {'adblock': False, 'adblock_aggressive': False, 'rpz': False, 'wildcard': False}, 'cli_testing': {'autocontinue': False, 'ci': {'active': False, 'branch': 'master', 'commit_message': 'PyFunceble - AutoSave', 'distribution_branch': 'master', 'end_commit_message': 'PyFunceble - Results', 'max_exec_minutes': 15}, 'cidr_expand': False, 'complements': False, 'cooldown_time': 0.0, 'days_between': {'db_clean': 28, 'db_retest': 1}, 'db_type': 'csv', 'display_mode': {'all': False, 'colour': True, 'dots': False, 'execution_time': False, 'less': True, 'percentage': True, 'quiet': False, 'simple': False, 'status': 'all'}, 'file_generation': {'analytic': True, 'hosts': False, 'no_file': False, 'plain': True, 'unified_results': False}, 'hosts_ip': '0.0.0.0', 'inactive_db': True, 'local_network': False, 'mining': False, 'preload_file': False, 'sorting_mode': {'hierarchical': False, 'standard': True}, 'testing_mode': {'availability': True, 'reputation': False, 'syntax': False}, 'whois_db': True}, 'command': '', 'command_before_end': '', 'cooldown_time': 0, 'custom_ip': '0.0.0.0', 'days_between_db_retest': 1, 'days_between_inactive_db_clean': 28, 'db_type': 'json', 'debug': {'active': False, 'level': 'info'}, 'dns': {'follow_server_order': True, 'protocol': 'UDP', 'trust_server': False}, 'dns_lookup_over_tcp': False, 'dns_server': None, 'filter': '', 'generate_complements': False, 'generate_hosts': True, 'generate_json': False, 'header_printed': False, 'hierarchical_sorting': False, 'http_codes': {'active': True, 'list': {'potentially_down': [400, 402, 404, 409, 410, 412, 414, 415, 416, 451], 'potentially_up': [0, 300, 301, 302, 303, 304, 305, 307, 308, 403, 405, 406, 407, 408, 411, 413, 417, 418, 421, 422, 423, 424, 426, 428, 431, 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511], 'up': [100, 101, 102, 200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 429]}, 'not_found_default': 'XXX', 'self_managed': False}, 'iana_whois_server': 'whois.iana.org', 'idna_conversion': False, 'inactive_database': True, 'less': True, 'links': {'api_date_format': 'https://pyfunceble.funilrys.com/api/date-format', 'api_no_referrer': 'https://pyfunceble.funilrys.com/api/no-referrer', 'config': 'https://raw.githubusercontent.com/funilrys/PyFunceble/dev/.PyFunceble_production.yaml', 'dir_structure': 'https://raw.githubusercontent.com/funilrys/PyFunceble/dev/dir_structure_production.json', 'iana': 'https://raw.githubusercontent.com/PyFunceble/iana/master/iana-domains-db.json', 'ipv4_reputation': 'https://reputation.alienvault.com/reputation.data', 'psl': 'https://raw.githubusercontent.com/PyFunceble/public-suffix/master/public-suffix.json', 'repo': 'https://github.com/funilrys/PyFunceble', 'requirements': 'https://raw.githubusercontent.com/funilrys/PyFunceble/dev/requirements.txt', 'user_agents': 'https://raw.githubusercontent.com/PyFunceble/user_agents/master/user_agents.json'}, 'local': False, 'logs': True, 'lookup': {'dns': True, 'http_status_code': True, 'netinfo': True, 'reputation': False, 'special': True, 'timeout': 5, 'whois': True}, 'maximal_processes': 8, 'mining': False, 'multiprocess': False, 'multiprocess_merging_mode': 'end', 'no_files': False, 'no_special': False, 'no_whois': False, 'outputs': {'analytic': {'directories': {'parent': 'Analytic/', 'potentially_down': 'POTENTIALLY_INACTIVE/', 'potentially_up': 'POTENTIALLY_ACTIVE/', 'suspicious': 'SUSPICIOUS/', 'up': 'ACTIVE/'}, 'filenames': {'potentially_down': 'down_or_potentially_down', 'potentially_up': 'potentially_up', 'suspicious': 'suspicious_and_merged_in_results', 'up': 'active_and_merged_in_results'}}, 'complements': {'directory': 'complements/'}, 'default_files': {'dir_structure': 'dir_structure.json', 'iana': 'iana-domains-db.json', 'inactive_db': 'inactive_db.json', 'mining': 'mining.json', 'public_suffix': 'public-suffix.json', 'results': 'results.txt', 'whois_db': 'whois_db.json'}, 'domains': {'directory': 'domains/', 'filename': 'list'}, 'hosts': {'directory': 'hosts/', 'filename': 'hosts', 'ip_filename': 'ips'}, 'json': {'directory': 'json/', 'filename': 'dump.json'}, 'logs': {'directories': {'parent': 'logs/', 'percentage': 'percentage/'}, 'filenames': {'auto_continue': 'continue.json', 'date_format': 'date_format.json', 'execution_time': 'execution_time.json', 'no_referrer': 'no_referrer.json', 'percentage': 'percentage.txt', 'whois': 'whois.json'}}, 'parent_directory': 'output/', 'splited': {'directory': 'splited/'}}, 'plain_list_domain': False, 'print_dots': False, 'quiet': False, 'reputation': False, 'rpz': False, 'shadow_file': False, 'share_logs': False, 'show_execution_time': False, 'show_percentage': True, 'simple': False, 'split': True, 'status': {'list': {'down': ['down', 'inactive', 'error'], 'generic': ['generic'], 'http_active': ['http_active'], 'invalid': ['ouch', 'invalid'], 'malicious': ['malicious', 'bad_actor'], 'potentially_down': ['potentially_down', 'potentially_inactive'], 'potentially_up': ['potentially_up', 'potentially_active'], 'sane': ['sane', 'safe'], 'suspicious': ['strange', 'suspicious', 'hum'], 'up': ['up', 'active'], 'valid': ['valid', 'syntax_valid', 'valid_syntax']}, 'official': {'down': 'INACTIVE', 'invalid': 'INVALID', 'malicious': 'MALICIOUS', 'sane': 'SANE', 'up': 'ACTIVE', 'valid': 'VALID'}}, 'store_whois_record': False, 'syntax': False, 'timeout': 3.0, 'unified': False, 'use_reputation_data': False, 'user_agent': {'browser': 'chrome', 'platform': 'linux', 'custom': None}, 'verify_ssl_certificate': False, 'whois_database': True, 'wildcard': False, 'travis_autosave_commit': None, 'travis_autosave_final_commit': None}
[2021-06-13 11:08:05,452::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/cli/execution_time.py:247@set_starting_time](PID2210639:MainProcess): Starting time: 1623568085.452744 | 2021-06-13 09:08:05.452744
[2021-06-13 11:08:05,453::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/engine/auto_save.py:77@__init__](PID2210639:MainProcess): Current CI engine: None
[2021-06-13 11:08:05,453::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/database/whois.py:83@__init__](PID2210639:MainProcess): DB (File): /home/funilrys/.config/PyFunceble/whois_db.json
[2021-06-13 11:08:05,454::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/engine/mining.py:85@__init__](PID2210639:MainProcess): Authorization: False
[2021-06-13 11:08:05,785::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/config/preset.py:201@disable](PID2210639:MainProcess): CONFIGURATION.show_percentage switched to False
[2021-06-13 11:08:05,785::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/config/preset.py:201@disable](PID2210639:MainProcess): CONFIGURATION.whois_database switched to False
[2021-06-13 11:08:05,786::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:100@__init__](PID2210639:MainProcess): Template: Less
[2021-06-13 11:08:05,786::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:101@__init__](PID2210639:MainProcess): Destination: None
[2021-06-13 11:08:05,786::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:102@__init__](PID2210639:MainProcess): Data to print:
None
[2021-06-13 11:08:05,786::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:103@__init__](PID2210639:MainProcess): Only print on file: False
[2021-06-13 11:08:05,787::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/status/gatherer_base.py:91@__init__](PID2210639:MainProcess): [github.com] File: None
[2021-06-13 11:08:05,788::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/status/gatherer_base.py:92@__init__](PID2210639:MainProcess): [github.com] Exclude file generation: False
[2021-06-13 11:08:05,790::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/referer.py:207@__init__](PID2210639:MainProcess): Extension to get the referer for: com
[2021-06-13 11:08:05,790::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/referer.py:258@get](PID2210639:MainProcess): Referer: whois.verisign-grs.com
[2021-06-13 11:08:05,791::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:255@a_record](PID2210639:MainProcess): Query over TCP: False
[2021-06-13 11:08:05,827::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/referer.py:262@get](PID2210639:MainProcess): Resolved Referer: ['192.34.234.30', '192.30.45.30']
[2021-06-13 11:08:05,827::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:255@a_record](PID2210639:MainProcess): Query over TCP: False
[2021-06-13 11:08:05,959::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/status/availability/domain_and_ip.py:162@__gather_extra_rules](PID2210639:MainProcess): [github.com] State before extra rules:
ACTIVE
[2021-06-13 11:08:05,960::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/http_code.py:128@__init__](PID2210639:MainProcess): Subject: 'http://github.com:80'
[2021-06-13 11:08:05,961::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/http_code.py:129@__init__](PID2210639:MainProcess): Headers:
{}
[2021-06-13 11:08:05,961::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/requests.py:318@head](PID2210639:MainProcess): Starting HEAD request to http://github.com:80 with {'timeout': 3.0, 'headers': {}, 'verify': False, 'allow_redirects': False}.
[2021-06-13 11:08:05,963::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:255@a_record](PID2210639:MainProcess): Query over TCP: False
[2021-06-13 11:08:06,071::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/requests.py:320@head](PID2210639:MainProcess): Finished HEAD request to http://github.com:80 with {'timeout': 3.0, 'headers': {}, 'verify': False, 'allow_redirects': False}.
[2021-06-13 11:08:06,072::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/http_code.py:165@_get_it](PID2210639:MainProcess): Status Code: 301
[2021-06-13 11:08:06,072::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/status/availability/extra_rules.py:115@__init__](PID2210639:MainProcess): [github.com] Headers:
{}
[2021-06-13 11:08:06,074::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:100@__init__](PID2210639:MainProcess): Template: Less
[2021-06-13 11:08:06,074::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:101@__init__](PID2210639:MainProcess): Destination: None
[2021-06-13 11:08:06,074::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:102@__init__](PID2210639:MainProcess): Data to print:
['github.com', 'ACTIVE', 301]
[2021-06-13 11:08:06,075::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:103@__init__](PID2210639:MainProcess): Only print on file: False
[2021-06-13 11:08:06,075::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/status/availability/domain_and_ip.py:227@__gather](PID2210639:MainProcess): [github.com] State:
{'_status_source': 'WHOIS', '_status': 'ACTIVE', 'dns_lookup': None, 'domain_syntax_validation': True, 'expiration_date': '09-oct-2022', 'given': 'github.com', 'http_status_code': 301, 'ipv4_range_syntax_validation': False, 'ipv4_syntax_validation': False, 'ipv6_range_syntax_validation': False, 'ipv6_syntax_validation': False, 'status_source': 'WHOIS', 'status': 'ACTIVE', 'subdomain_syntax_validation': False, 'tested': 'github.com', 'url_syntax_validation': False, 'whois_record': '   Domain Name: GITHUB.COM\r\n   Registry Domain ID: 1264983250_DOMAIN_COM-VRSN\r\n   Registrar WHOIS Server: whois.markmonitor.com\r\n   Registrar URL: http://www.markmonitor.com\r\n   Updated Date: 2020-09-08T09:18:27Z\r\n   Creation Date: 2007-10-09T18:20:50Z\r\n   Registry Expiry Date: 2022-10-09T18:20:50Z\r\n   Registrar: MarkMonitor Inc.\r\n   Registrar IANA ID: 292\r\n   Registrar Abuse Contact Email: abusecomplaints@markmonitor.com\r\n   Registrar Abuse Contact Phone: +1.2083895740\r\n   Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited\r\n   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited\r\n   Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited\r\n   Name Server: DNS1.P08.NSONE.NET\r\n   Name Server: DNS2.P08.NSONE.NET\r\n   Name Server: DNS3.P08.NSONE.NET\r\n   Name Server: DNS4.P08.NSONE.NET\r\n   Name Server: NS-1283.AWSDNS-32.ORG\r\n   Name Server: NS-1707.AWSDNS-21.CO.UK\r\n   Name Server: NS-421.AWSDNS-52.COM\r\n   Name Server: NS-520.AWSDNS-01.NET\r\n   DNSSEC: unsigned\r\n   URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/\r\n>>> Last update of whois database: 2021-06-13T09:08:01Z <<<\r\n\r\nFor more information on Whois status codes, please visit https://icann.org/epp\r\n\r\nNOTICE: The expiration date displayed in this record is the date the\r\nregistrar\'s sponsorship of the domain name registration in the registry is\r\ncurrently set to expire. This date does not necessarily reflect the expiration\r\ndate of the domain name registrant\'s agreement with the sponsoring\r\nregistrar.  Users may consult the sponsoring registrar\'s Whois database to\r\nview the registrar\'s reported date of expiration for this registration.\r\n\r\nTERMS OF USE: You are not authorized to access or query our Whois\r\ndatabase through the use of electronic processes that are high-volume and\r\nautomated except as reasonably necessary to register domain names or\r\nmodify existing registrations; the Data in VeriSign Global Registry\r\nServices\' ("VeriSign") Whois database is provided by VeriSign for\r\ninformation purposes only, and to assist persons in obtaining information\r\nabout or related to a domain name registration record. VeriSign does not\r\nguarantee its accuracy. By submitting a Whois query, you agree to abide\r\nby the following terms of use: You agree that you may use this Data only\r\nfor lawful purposes and that under no circumstances will you use this Data\r\nto: (1) allow, enable, or otherwise support the transmission of mass\r\nunsolicited, commercial advertising or solicitations via e-mail, telephone,\r\nor facsimile; or (2) enable high volume, automated, electronic processes\r\nthat apply to VeriSign (or its computer systems). The compilation,\r\nrepackaging, dissemination or other use of this Data is expressly\r\nprohibited without the prior written consent of VeriSign. You agree not to\r\nuse electronic processes that are automated and high-volume to access or\r\nquery the Whois database except as reasonably necessary to register\r\ndomain names or modify existing registrations. VeriSign reserves the right\r\nto restrict your access to the Whois database in its sole discretion to ensure\r\noperational stability.  VeriSign may restrict or terminate your access to the\r\nWhois database for failure to abide by these terms of use. VeriSign\r\nreserves the right to modify these terms at any time.\r\n\r\nThe Registry database contains ONLY .COM, .NET, .EDU domains and\r\nRegistrars.\r\n', 'whois_server': 'whois.verisign-grs.com'}
[2021-06-13 11:08:06,076::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/cli/execution_time.py:261@set_stoping_time](PID2210639:MainProcess): Stoping time: 1623568085.452744 | 2021-06-13 09:08:06.076406
[2021-06-13 11:08:14,799::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:83@__init__](PID2210930:MainProcess): DNS Resolver Nameservers: ['1.1.1.1', '1.0.0.1', 'fd00::cece:1eff:fef3:5c2e', '2606:4700:4700::1111', '2606:4700:4700::1001']
[2021-06-13 11:08:14,799::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:86@__init__](PID2210930:MainProcess): DNS Resolver (Nameservers) Port: {}
[2021-06-13 11:08:14,800::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:89@__init__](PID2210930:MainProcess): DNS Resolver Port: 53
[2021-06-13 11:08:14,800::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:90@__init__](PID2210930:MainProcess): DNS Resolver timeout: 2.0
[2021-06-13 11:08:14,800::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:91@__init__](PID2210930:MainProcess): DNS Resolver lifetime: 5.0
[2021-06-13 11:08:14,800::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:92@__init__](PID2210930:MainProcess): DNS Resolver over TCP: False
[2021-06-13 11:08:14,803::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/config/preset.py:418@timeout](PID2210930:MainProcess): CONFIGURATION.timeout switched to 3.0
[2021-06-13 11:08:14,970::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/cli/dispatcher.py:118@__init__](PID2210930:MainProcess): CONFIGURATION:
{'adblock': False, 'aggressive': False, 'auto_continue': True, 'ci': False, 'ci_autosave_commit': 'PyFunceble - AutoSave', 'ci_autosave_final_commit': 'PyFunceble - Results', 'ci_autosave_minutes': 15, 'ci_branch': 'master', 'ci_distribution_branch': 'master', 'cli_decoding': {'adblock': False, 'adblock_aggressive': False, 'rpz': False, 'wildcard': False}, 'cli_testing': {'autocontinue': False, 'ci': {'active': False, 'branch': 'master', 'commit_message': 'PyFunceble - AutoSave', 'distribution_branch': 'master', 'end_commit_message': 'PyFunceble - Results', 'max_exec_minutes': 15}, 'cidr_expand': False, 'complements': False, 'cooldown_time': 0.0, 'days_between': {'db_clean': 28, 'db_retest': 1}, 'db_type': 'csv', 'display_mode': {'all': False, 'colour': True, 'dots': False, 'execution_time': False, 'less': True, 'percentage': True, 'quiet': False, 'simple': False, 'status': 'all'}, 'file_generation': {'analytic': True, 'hosts': False, 'no_file': False, 'plain': True, 'unified_results': False}, 'hosts_ip': '0.0.0.0', 'inactive_db': True, 'local_network': False, 'mining': False, 'preload_file': False, 'sorting_mode': {'hierarchical': False, 'standard': True}, 'testing_mode': {'availability': True, 'reputation': False, 'syntax': False}, 'whois_db': True}, 'command': '', 'command_before_end': '', 'cooldown_time': 0, 'custom_ip': '0.0.0.0', 'days_between_db_retest': 1, 'days_between_inactive_db_clean': 28, 'db_type': 'json', 'debug': {'active': False, 'level': 'info'}, 'dns': {'follow_server_order': True, 'protocol': 'UDP', 'trust_server': False}, 'dns_lookup_over_tcp': False, 'dns_server': None, 'filter': '', 'generate_complements': False, 'generate_hosts': True, 'generate_json': False, 'header_printed': False, 'hierarchical_sorting': False, 'http_codes': {'active': True, 'list': {'potentially_down': [400, 402, 404, 409, 410, 412, 414, 415, 416, 451], 'potentially_up': [0, 300, 301, 302, 303, 304, 305, 307, 308, 403, 405, 406, 407, 408, 411, 413, 417, 418, 421, 422, 423, 424, 426, 428, 431, 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511], 'up': [100, 101, 102, 200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 429]}, 'not_found_default': 'XXX', 'self_managed': False}, 'iana_whois_server': 'whois.iana.org', 'idna_conversion': False, 'inactive_database': True, 'less': True, 'links': {'api_date_format': 'https://pyfunceble.funilrys.com/api/date-format', 'api_no_referrer': 'https://pyfunceble.funilrys.com/api/no-referrer', 'config': 'https://raw.githubusercontent.com/funilrys/PyFunceble/dev/.PyFunceble_production.yaml', 'dir_structure': 'https://raw.githubusercontent.com/funilrys/PyFunceble/dev/dir_structure_production.json', 'iana': 'https://raw.githubusercontent.com/PyFunceble/iana/master/iana-domains-db.json', 'ipv4_reputation': 'https://reputation.alienvault.com/reputation.data', 'psl': 'https://raw.githubusercontent.com/PyFunceble/public-suffix/master/public-suffix.json', 'repo': 'https://github.com/funilrys/PyFunceble', 'requirements': 'https://raw.githubusercontent.com/funilrys/PyFunceble/dev/requirements.txt', 'user_agents': 'https://raw.githubusercontent.com/PyFunceble/user_agents/master/user_agents.json'}, 'local': False, 'logs': True, 'lookup': {'dns': True, 'http_status_code': True, 'netinfo': True, 'reputation': False, 'special': True, 'timeout': 5, 'whois': True}, 'maximal_processes': 8, 'mining': False, 'multiprocess': False, 'multiprocess_merging_mode': 'end', 'no_files': False, 'no_special': False, 'no_whois': False, 'outputs': {'analytic': {'directories': {'parent': 'Analytic/', 'potentially_down': 'POTENTIALLY_INACTIVE/', 'potentially_up': 'POTENTIALLY_ACTIVE/', 'suspicious': 'SUSPICIOUS/', 'up': 'ACTIVE/'}, 'filenames': {'potentially_down': 'down_or_potentially_down', 'potentially_up': 'potentially_up', 'suspicious': 'suspicious_and_merged_in_results', 'up': 'active_and_merged_in_results'}}, 'complements': {'directory': 'complements/'}, 'default_files': {'dir_structure': 'dir_structure.json', 'iana': 'iana-domains-db.json', 'inactive_db': 'inactive_db.json', 'mining': 'mining.json', 'public_suffix': 'public-suffix.json', 'results': 'results.txt', 'whois_db': 'whois_db.json'}, 'domains': {'directory': 'domains/', 'filename': 'list'}, 'hosts': {'directory': 'hosts/', 'filename': 'hosts', 'ip_filename': 'ips'}, 'json': {'directory': 'json/', 'filename': 'dump.json'}, 'logs': {'directories': {'parent': 'logs/', 'percentage': 'percentage/'}, 'filenames': {'auto_continue': 'continue.json', 'date_format': 'date_format.json', 'execution_time': 'execution_time.json', 'no_referrer': 'no_referrer.json', 'percentage': 'percentage.txt', 'whois': 'whois.json'}}, 'parent_directory': 'output/', 'splited': {'directory': 'splited/'}}, 'plain_list_domain': False, 'print_dots': False, 'quiet': False, 'reputation': False, 'rpz': False, 'shadow_file': False, 'share_logs': False, 'show_execution_time': False, 'show_percentage': True, 'simple': False, 'split': True, 'status': {'list': {'down': ['down', 'inactive', 'error'], 'generic': ['generic'], 'http_active': ['http_active'], 'invalid': ['ouch', 'invalid'], 'malicious': ['malicious', 'bad_actor'], 'potentially_down': ['potentially_down', 'potentially_inactive'], 'potentially_up': ['potentially_up', 'potentially_active'], 'sane': ['sane', 'safe'], 'suspicious': ['strange', 'suspicious', 'hum'], 'up': ['up', 'active'], 'valid': ['valid', 'syntax_valid', 'valid_syntax']}, 'official': {'down': 'INACTIVE', 'invalid': 'INVALID', 'malicious': 'MALICIOUS', 'sane': 'SANE', 'up': 'ACTIVE', 'valid': 'VALID'}}, 'store_whois_record': False, 'syntax': False, 'timeout': 3.0, 'unified': False, 'use_reputation_data': False, 'user_agent': {'browser': 'chrome', 'platform': 'linux', 'custom': None}, 'verify_ssl_certificate': False, 'whois_database': True, 'wildcard': False, 'travis_autosave_commit': None, 'travis_autosave_final_commit': None}
[2021-06-13 11:08:14,970::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/cli/execution_time.py:247@set_starting_time](PID2210930:MainProcess): Starting time: 1623568094.970185 | 2021-06-13 09:08:14.970185
[2021-06-13 11:08:14,971::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/engine/auto_save.py:77@__init__](PID2210930:MainProcess): Current CI engine: None
[2021-06-13 11:08:14,971::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/database/whois.py:83@__init__](PID2210930:MainProcess): DB (File): /home/funilrys/.config/PyFunceble/whois_db.json
[2021-06-13 11:08:14,971::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/engine/mining.py:85@__init__](PID2210930:MainProcess): Authorization: False
[2021-06-13 11:08:14,972::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/config/preset.py:201@disable](PID2210930:MainProcess): CONFIGURATION.show_percentage switched to False
[2021-06-13 11:08:14,972::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/config/preset.py:201@disable](PID2210930:MainProcess): CONFIGURATION.whois_database switched to False
[2021-06-13 11:08:14,972::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:100@__init__](PID2210930:MainProcess): Template: Less
[2021-06-13 11:08:14,972::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:101@__init__](PID2210930:MainProcess): Destination: None
[2021-06-13 11:08:14,972::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:102@__init__](PID2210930:MainProcess): Data to print:
None
[2021-06-13 11:08:14,973::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:103@__init__](PID2210930:MainProcess): Only print on file: False
[2021-06-13 11:08:14,973::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/status/gatherer_base.py:91@__init__](PID2210930:MainProcess): [github.com] File: None
[2021-06-13 11:08:14,973::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/status/gatherer_base.py:92@__init__](PID2210930:MainProcess): [github.com] Exclude file generation: False
[2021-06-13 11:08:14,975::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/referer.py:207@__init__](PID2210930:MainProcess): Extension to get the referer for: com
[2021-06-13 11:08:14,975::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/referer.py:258@get](PID2210930:MainProcess): Referer: whois.verisign-grs.com
[2021-06-13 11:08:14,975::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:255@a_record](PID2210930:MainProcess): Query over TCP: False
[2021-06-13 11:08:15,010::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/referer.py:262@get](PID2210930:MainProcess): Resolved Referer: ['192.30.45.30', '192.34.234.30']
[2021-06-13 11:08:15,011::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:255@a_record](PID2210930:MainProcess): Query over TCP: False
[2021-06-13 11:08:15,118::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/status/availability/domain_and_ip.py:162@__gather_extra_rules](PID2210930:MainProcess): [github.com] State before extra rules:
ACTIVE
[2021-06-13 11:08:15,119::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/http_code.py:128@__init__](PID2210930:MainProcess): Subject: 'http://github.com:80'
[2021-06-13 11:08:15,119::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/http_code.py:129@__init__](PID2210930:MainProcess): Headers:
{}
[2021-06-13 11:08:15,120::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/requests.py:318@head](PID2210930:MainProcess): Starting HEAD request to http://github.com:80 with {'timeout': 3.0, 'headers': {}, 'verify': False, 'allow_redirects': False}.
[2021-06-13 11:08:15,121::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/dns.py:255@a_record](PID2210930:MainProcess): Query over TCP: False
[2021-06-13 11:08:15,224::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/requests.py:320@head](PID2210930:MainProcess): Finished HEAD request to http://github.com:80 with {'timeout': 3.0, 'headers': {}, 'verify': False, 'allow_redirects': False}.
[2021-06-13 11:08:15,225::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/lookup/http_code.py:165@_get_it](PID2210930:MainProcess): Status Code: 301
[2021-06-13 11:08:15,226::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/status/availability/extra_rules.py:115@__init__](PID2210930:MainProcess): [github.com] Headers:
{}
[2021-06-13 11:08:15,227::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:100@__init__](PID2210930:MainProcess): Template: Less
[2021-06-13 11:08:15,228::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:101@__init__](PID2210930:MainProcess): Destination: None
[2021-06-13 11:08:15,228::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:102@__init__](PID2210930:MainProcess): Data to print:
['github.com', 'ACTIVE', 301]
[2021-06-13 11:08:15,228::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/output/prints.py:103@__init__](PID2210930:MainProcess): Only print on file: False
[2021-06-13 11:08:15,229::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/status/availability/domain_and_ip.py:227@__gather](PID2210930:MainProcess): [github.com] State:
{'_status_source': 'WHOIS', '_status': 'ACTIVE', 'dns_lookup': None, 'domain_syntax_validation': True, 'expiration_date': '09-oct-2022', 'given': 'github.com', 'http_status_code': 301, 'ipv4_range_syntax_validation': False, 'ipv4_syntax_validation': False, 'ipv6_range_syntax_validation': False, 'ipv6_syntax_validation': False, 'status_source': 'WHOIS', 'status': 'ACTIVE', 'subdomain_syntax_validation': False, 'tested': 'github.com', 'url_syntax_validation': False, 'whois_record': '   Domain Name: GITHUB.COM\r\n   Registry Domain ID: 1264983250_DOMAIN_COM-VRSN\r\n   Registrar WHOIS Server: whois.markmonitor.com\r\n   Registrar URL: http://www.markmonitor.com\r\n   Updated Date: 2020-09-08T09:18:27Z\r\n   Creation Date: 2007-10-09T18:20:50Z\r\n   Registry Expiry Date: 2022-10-09T18:20:50Z\r\n   Registrar: MarkMonitor Inc.\r\n   Registrar IANA ID: 292\r\n   Registrar Abuse Contact Email: abusecomplaints@markmonitor.com\r\n   Registrar Abuse Contact Phone: +1.2083895740\r\n   Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited\r\n   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited\r\n   Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited\r\n   Name Server: DNS1.P08.NSONE.NET\r\n   Name Server: DNS2.P08.NSONE.NET\r\n   Name Server: DNS3.P08.NSONE.NET\r\n   Name Server: DNS4.P08.NSONE.NET\r\n   Name Server: NS-1283.AWSDNS-32.ORG\r\n   Name Server: NS-1707.AWSDNS-21.CO.UK\r\n   Name Server: NS-421.AWSDNS-52.COM\r\n   Name Server: NS-520.AWSDNS-01.NET\r\n   DNSSEC: unsigned\r\n   URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/\r\n>>> Last update of whois database: 2021-06-13T09:08:01Z <<<\r\n\r\nFor more information on Whois status codes, please visit https://icann.org/epp\r\n\r\nNOTICE: The expiration date displayed in this record is the date the\r\nregistrar\'s sponsorship of the domain name registration in the registry is\r\ncurrently set to expire. This date does not necessarily reflect the expiration\r\ndate of the domain name registrant\'s agreement with the sponsoring\r\nregistrar.  Users may consult the sponsoring registrar\'s Whois database to\r\nview the registrar\'s reported date of expiration for this registration.\r\n\r\nTERMS OF USE: You are not authorized to access or query our Whois\r\ndatabase through the use of electronic processes that are high-volume and\r\nautomated except as reasonably necessary to register domain names or\r\nmodify existing registrations; the Data in VeriSign Global Registry\r\nServices\' ("VeriSign") Whois database is provided by VeriSign for\r\ninformation purposes only, and to assist persons in obtaining information\r\nabout or related to a domain name registration record. VeriSign does not\r\nguarantee its accuracy. By submitting a Whois query, you agree to abide\r\nby the following terms of use: You agree that you may use this Data only\r\nfor lawful purposes and that under no circumstances will you use this Data\r\nto: (1) allow, enable, or otherwise support the transmission of mass\r\nunsolicited, commercial advertising or solicitations via e-mail, telephone,\r\nor facsimile; or (2) enable high volume, automated, electronic processes\r\nthat apply to VeriSign (or its computer systems). The compilation,\r\nrepackaging, dissemination or other use of this Data is expressly\r\nprohibited without the prior written consent of VeriSign. You agree not to\r\nuse electronic processes that are automated and high-volume to access or\r\nquery the Whois database except as reasonably necessary to register\r\ndomain names or modify existing registrations. VeriSign reserves the right\r\nto restrict your access to the Whois database in its sole discretion to ensure\r\noperational stability.  VeriSign may restrict or terminate your access to the\r\nWhois database for failure to abide by these terms of use. VeriSign\r\nreserves the right to modify these terms at any time.\r\n\r\nThe Registry database contains ONLY .COM, .NET, .EDU domains and\r\nRegistrars.\r\n', 'whois_server': 'whois.verisign-grs.com'}
[2021-06-13 11:08:15,230::DEBUG::/usr/lib/python3.9/site-packages/PyFunceble/cli/execution_time.py:261@set_stoping_time](PID2210930:MainProcess): Stoping time: 1623568094.970185 | 2021-06-13 09:08:15.230325
